// <auto-generated />
using System;
using Atracciones.MsReservas.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atracciones.MsReservas.DataAccess.Migrations
{
    [DbContext(typeof(VentasDbContext))]
    [Migration("20260510204836_InitialVentas")]
    partial class InitialVentas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ventas")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atracciones.MsReservas.DataAccess.Entities.ReservaDetalleEntity", b =>
                {
                    b.Property<Guid>("RdetGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rdet_guid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("PrecioUnit")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_unit");

                    b.Property<Guid>("RevGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("rev_guid");

                    b.Property<decimal>("SubtotalLinea")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal_linea");

                    b.Property<Guid>("TckGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("tck_guid");

                    b.Property<string>("TipoParticipante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_participante");

                    b.HasKey("RdetGuid");

                    b.HasIndex("RevGuid");

                    b.ToTable("reserva_detalle", "ventas");
                });

            modelBuilder.Entity("Atracciones.MsReservas.DataAccess.Entities.ReservaEntity", b =>
                {
                    b.Property<Guid>("RevGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rev_guid");

                    b.Property<Guid>("AtGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("at_guid");

                    b.Property<string>("AtraccionNombreSnap")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("atraccion_nombre_snap");

                    b.Property<Guid>("CliGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("cli_guid");

                    b.Property<string>("HorFechaSnap")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("hor_fecha_snap");

                    b.Property<Guid>("HorGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("hor_guid");

                    b.Property<string>("HorHoraFinSnap")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("hor_hora_fin_snap");

                    b.Property<string>("HorHoraInicioSnap")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("hor_hora_inicio_snap");

                    b.Property<string>("RevCodigo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rev_codigo");

                    b.Property<char>("RevEstado")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("rev_estado")
                        .IsFixedLength();

                    b.Property<DateTime>("RevFechaReservaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rev_fecha_reserva_utc");

                    b.Property<string>("RevIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rev_ip_ingreso");

                    b.Property<string>("RevMoneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("USD")
                        .HasColumnName("rev_moneda");

                    b.Property<string>("RevOrigenCanal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rev_origen_canal");

                    b.Property<decimal>("RevSubtotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("rev_subtotal");

                    b.Property<decimal>("RevTotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("rev_total");

                    b.Property<string>("RevUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rev_usuario_ingreso");

                    b.Property<decimal>("RevValorIva")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("rev_valor_iva");

                    b.HasKey("RevGuid");

                    b.HasIndex("CliGuid");

                    b.HasIndex("RevCodigo")
                        .IsUnique();

                    b.ToTable("reservas", "ventas");
                });

            modelBuilder.Entity("Atracciones.MsReservas.DataAccess.Entities.ReservaDetalleEntity", b =>
                {
                    b.HasOne("Atracciones.MsReservas.DataAccess.Entities.ReservaEntity", "Reserva")
                        .WithMany("Detalle")
                        .HasForeignKey("RevGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Atracciones.MsReservas.DataAccess.Entities.ReservaEntity", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
