// <auto-generated />
using System;
using Atracciones.MsReservas.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atracciones.MsReservas.DataAccess.Migrations.Crm
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crm")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atracciones.MsReservas.DataAccess.Entities.ClienteEntity", b =>
                {
                    b.Property<Guid>("CliGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cli_guid");

                    b.Property<string>("CliApellidos")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cli_apellidos");

                    b.Property<string>("CliCorreo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cli_correo");

                    b.Property<string>("CliDireccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cli_direccion");

                    b.Property<char>("CliEstado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("cli_estado")
                        .IsFixedLength();

                    b.Property<DateTime>("CliFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cli_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("CliIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cli_ip_ingreso");

                    b.Property<string>("CliNombres")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cli_nombres");

                    b.Property<string>("CliNumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cli_numero_identificacion");

                    b.Property<string>("CliRazonSocial")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cli_razon_social");

                    b.Property<string>("CliTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cli_telefono");

                    b.Property<string>("CliTipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cli_tipo_identificacion");

                    b.Property<string>("CliUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cli_usuario_ingreso");

                    b.HasKey("CliGuid");

                    b.HasIndex("CliNumeroIdentificacion")
                        .IsUnique();

                    b.ToTable("clientes", "crm");
                });
#pragma warning restore 612, 618
        }
    }
}
