// <auto-generated />
using System;
using Atracciones.MsIdentidad.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atracciones.MsIdentidad.DataAccess.Migrations
{
    [DbContext(typeof(IdentidadDbContext))]
    [Migration("20260510022937_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auth")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atracciones.MsIdentidad.DataAccess.Entities.RolEntity", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolDescripcion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("rol_descripcion");

                    b.Property<char>("RolEstado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("rol_estado")
                        .IsFixedLength();

                    b.Property<Guid>("RolGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rol_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("RolId");

                    b.HasIndex("RolDescripcion")
                        .IsUnique();

                    b.ToTable("roles", "auth");
                });

            modelBuilder.Entity("Atracciones.MsIdentidad.DataAccess.Entities.UsuarioEntity", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuId"));

                    b.Property<int?>("CliId")
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    b.Property<char>("UsuEstado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("usu_estado")
                        .IsFixedLength();

                    b.Property<DateTime>("UsuFechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usu_fecha_registro")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("UsuGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usu_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("UsuIpRegistro")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("usu_ip_registro");

                    b.Property<string>("UsuLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usu_login");

                    b.Property<string>("UsuPasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("usu_password_hash");

                    b.Property<string>("UsuUsuarioRegistro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usu_usuario_registro");

                    b.HasKey("UsuId");

                    b.HasIndex("UsuGuid")
                        .IsUnique();

                    b.HasIndex("UsuLogin")
                        .IsUnique();

                    b.ToTable("usuarios", "auth");
                });

            modelBuilder.Entity("Atracciones.MsIdentidad.DataAccess.Entities.UsuarioRolEntity", b =>
                {
                    b.Property<int>("UsuId")
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<char>("UsuRolEstado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("usu_rol_estado")
                        .IsFixedLength();

                    b.HasKey("UsuId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("usuario_roles", "auth");
                });

            modelBuilder.Entity("Atracciones.MsIdentidad.DataAccess.Entities.UsuarioRolEntity", b =>
                {
                    b.HasOne("Atracciones.MsIdentidad.DataAccess.Entities.RolEntity", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atracciones.MsIdentidad.DataAccess.Entities.UsuarioEntity", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Atracciones.MsIdentidad.DataAccess.Entities.RolEntity", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Atracciones.MsIdentidad.DataAccess.Entities.UsuarioEntity", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
