// <auto-generated />
using System;
using Atracciones.MsOrquestador.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atracciones.MsOrquestador.DataAccess.Migrations
{
    [DbContext(typeof(OrquestadorDbContext))]
    [Migration("20260517225722_PayPalCheckoutPayload")]
    partial class PayPalCheckoutPayload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orq")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atracciones.MsOrquestador.DataAccess.Entities.IdempotencyKeyEntity", b =>
                {
                    b.Property<string>("StorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_json");

                    b.HasKey("StorageKey");

                    b.ToTable("idempotency_keys", "orq");
                });

            modelBuilder.Entity("Atracciones.MsOrquestador.DataAccess.Entities.PayPalPaymentEntity", b =>
                {
                    b.Property<long>("PayPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pay_payment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PayPaymentId"));

                    b.Property<string>("ChargebackStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("chargeback_status");

                    b.Property<string>("CheckoutPayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("checkout_payload_json");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado_pago");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("moneda");

                    b.Property<decimal>("MontoEsperado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_esperado");

                    b.Property<string>("PaypalCaptureId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("paypal_capture_id");

                    b.Property<string>("PaypalOrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("paypal_order_id");

                    b.Property<Guid>("RevGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("rev_guid");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("PayPaymentId");

                    b.HasIndex("PaypalCaptureId")
                        .IsUnique();

                    b.HasIndex("PaypalOrderId")
                        .IsUnique();

                    b.ToTable("paypal_payments", "orq");
                });

            modelBuilder.Entity("Atracciones.MsOrquestador.DataAccess.Entities.SagaPasoEntity", b =>
                {
                    b.Property<long>("PasoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("paso_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PasoId"));

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_utc");

                    b.Property<string>("Paso")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("paso");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("text")
                        .HasColumnName("request_payload");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("text")
                        .HasColumnName("response_payload");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.HasKey("PasoId");

                    b.HasIndex("SagaId");

                    b.ToTable("saga_pasos", "orq");
                });

            modelBuilder.Entity("Atracciones.MsOrquestador.DataAccess.Entities.SagaStateEntity", b =>
                {
                    b.Property<Guid>("SagaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FinUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin_utc");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio_utc");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tipo");

                    b.HasKey("SagaId");

                    b.ToTable("saga_state", "orq");
                });

            modelBuilder.Entity("Atracciones.MsOrquestador.DataAccess.Entities.SagaPasoEntity", b =>
                {
                    b.HasOne("Atracciones.MsOrquestador.DataAccess.Entities.SagaStateEntity", "Saga")
                        .WithMany("Pasos")
                        .HasForeignKey("SagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Saga");
                });

            modelBuilder.Entity("Atracciones.MsOrquestador.DataAccess.Entities.SagaStateEntity", b =>
                {
                    b.Navigation("Pasos");
                });
#pragma warning restore 612, 618
        }
    }
}
