// <auto-generated />
using System;
using Atracciones.MsCatalogos.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atracciones.MsCatalogos.DataAccess.Migrations
{
    [DbContext(typeof(CatalogosDbContext))]
    partial class CatalogosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalogos")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atracciones.MsCatalogos.DataAccess.Entities.CategoriaEntity", b =>
                {
                    b.Property<Guid>("CatGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cat_guid");

                    b.Property<char>("CatEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("cat_estado");

                    b.Property<DateTime?>("CatFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cat_fecha_eliminacion");

                    b.Property<DateTime>("CatFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cat_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("CatFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cat_fecha_mod");

                    b.Property<string>("CatIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cat_ip_eliminacion");

                    b.Property<string>("CatIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cat_ip_ingreso");

                    b.Property<string>("CatIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cat_ip_mod");

                    b.Property<string>("CatNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cat_nombre");

                    b.Property<Guid?>("CatParentGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("cat_parent_guid");

                    b.Property<string>("CatUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cat_usuario_eliminacion");

                    b.Property<string>("CatUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cat_usuario_ingreso");

                    b.Property<string>("CatUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cat_usuario_mod");

                    b.HasKey("CatGuid");

                    b.HasIndex("CatParentGuid");

                    b.ToTable("categorias", "catalogos");
                });

            modelBuilder.Entity("Atracciones.MsCatalogos.DataAccess.Entities.DestinoEntity", b =>
                {
                    b.Property<Guid>("DesGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("des_guid");

                    b.Property<char>("DesEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("des_estado");

                    b.Property<DateTime?>("DesFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("des_fecha_eliminacion");

                    b.Property<DateTime>("DesFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("des_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("DesFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("des_fecha_mod");

                    b.Property<string>("DesImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("des_imagen_url");

                    b.Property<string>("DesIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("des_ip_eliminacion");

                    b.Property<string>("DesIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("des_ip_ingreso");

                    b.Property<string>("DesIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("des_ip_mod");

                    b.Property<string>("DesNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("des_nombre");

                    b.Property<string>("DesPais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("des_pais");

                    b.Property<string>("DesUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("des_usuario_eliminacion");

                    b.Property<string>("DesUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("des_usuario_ingreso");

                    b.Property<string>("DesUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("des_usuario_mod");

                    b.HasKey("DesGuid");

                    b.ToTable("destinos", "catalogos");
                });

            modelBuilder.Entity("Atracciones.MsCatalogos.DataAccess.Entities.IdiomaEntity", b =>
                {
                    b.Property<Guid>("IdGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_guid");

                    b.Property<string>("IdDescripcion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("id_descripcion");

                    b.Property<char>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("id_estado");

                    b.Property<DateTime?>("IdFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("id_fecha_eliminacion");

                    b.Property<DateTime>("IdFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("id_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("IdFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("id_fecha_mod");

                    b.Property<string>("IdIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("id_ip_eliminacion");

                    b.Property<string>("IdIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("id_ip_ingreso");

                    b.Property<string>("IdIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("id_ip_mod");

                    b.Property<string>("IdUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_usuario_eliminacion");

                    b.Property<string>("IdUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_usuario_ingreso");

                    b.Property<string>("IdUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_usuario_mod");

                    b.HasKey("IdGuid");

                    b.HasIndex("IdDescripcion")
                        .IsUnique()
                        .HasDatabaseName("uk_idiomas_descripcion");

                    b.ToTable("idiomas", "catalogos");
                });

            modelBuilder.Entity("Atracciones.MsCatalogos.DataAccess.Entities.ImagenEntity", b =>
                {
                    b.Property<Guid>("ImgGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("img_guid");

                    b.Property<string>("ImgDescripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("img_descripcion");

                    b.Property<char>("ImgEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("img_estado");

                    b.Property<DateTime?>("ImgFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("img_fecha_eliminacion");

                    b.Property<DateTime>("ImgFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("img_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("ImgFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("img_fecha_mod");

                    b.Property<string>("ImgIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("img_ip_eliminacion");

                    b.Property<string>("ImgIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("img_ip_ingreso");

                    b.Property<string>("ImgIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("img_ip_mod");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("img_url");

                    b.Property<string>("ImgUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("img_usuario_eliminacion");

                    b.Property<string>("ImgUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("img_usuario_ingreso");

                    b.Property<string>("ImgUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("img_usuario_mod");

                    b.HasKey("ImgGuid");

                    b.ToTable("imagenes", "catalogos");
                });

            modelBuilder.Entity("Atracciones.MsCatalogos.DataAccess.Entities.IncluyeEntity", b =>
                {
                    b.Property<Guid>("IncGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("inc_guid");

                    b.Property<string>("IncDescripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("inc_descripcion");

                    b.Property<char>("IncEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("inc_estado");

                    b.HasKey("IncGuid");

                    b.ToTable("incluye", "catalogos");
                });

            modelBuilder.Entity("Atracciones.MsCatalogos.DataAccess.Entities.CategoriaEntity", b =>
                {
                    b.HasOne("Atracciones.MsCatalogos.DataAccess.Entities.CategoriaEntity", null)
                        .WithMany()
                        .HasForeignKey("CatParentGuid")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
