// <auto-generated />
using System;
using Atracciones.MsFacturacion.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atracciones.MsFacturacion.DataAccess.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atracciones.MsFacturacion.DataAccess.Entities.DatosFacturacionEntity", b =>
                {
                    b.Property<Guid>("DfacGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("dfac_guid");

                    b.Property<string>("DfacCorreo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("dfac_correo");

                    b.Property<string>("DfacNombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("dfac_nombre");

                    b.Property<string>("DfacTelefono")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("dfac_telefono");

                    b.Property<Guid>("FacGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("fac_guid");

                    b.HasKey("DfacGuid");

                    b.HasIndex("FacGuid")
                        .IsUnique();

                    b.ToTable("datos_facturacion", "billing");
                });

            modelBuilder.Entity("Atracciones.MsFacturacion.DataAccess.Entities.FacturaEntity", b =>
                {
                    b.Property<Guid>("FacGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fac_guid");

                    b.Property<Guid>("CliGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("cli_guid");

                    b.Property<char>("FacEstado")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasColumnName("fac_estado")
                        .IsFixedLength();

                    b.Property<DateTime>("FacFechaEmisionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fac_fecha_emision_utc");

                    b.Property<string>("FacIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("fac_ip_ingreso");

                    b.Property<string>("FacMoneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("USD")
                        .HasColumnName("fac_moneda");

                    b.Property<string>("FacNumero")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("fac_numero");

                    b.Property<decimal>("FacTotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("fac_total");

                    b.Property<string>("FacUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fac_usuario_ingreso");

                    b.Property<string>("RevCodigoSnap")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rev_codigo_snap");

                    b.Property<Guid>("RevGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("rev_guid");

                    b.HasKey("FacGuid");

                    b.HasIndex("CliGuid");

                    b.HasIndex("FacNumero")
                        .IsUnique();

                    b.HasIndex("RevGuid")
                        .IsUnique();

                    b.ToTable("facturas", "billing");
                });

            modelBuilder.Entity("Atracciones.MsFacturacion.DataAccess.Entities.DatosFacturacionEntity", b =>
                {
                    b.HasOne("Atracciones.MsFacturacion.DataAccess.Entities.FacturaEntity", "Factura")
                        .WithOne("Datos")
                        .HasForeignKey("Atracciones.MsFacturacion.DataAccess.Entities.DatosFacturacionEntity", "FacGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Atracciones.MsFacturacion.DataAccess.Entities.FacturaEntity", b =>
                {
                    b.Navigation("Datos");
                });
#pragma warning restore 612, 618
        }
    }
}
