// <auto-generated />
using System;
using Atracciones.MsAuditoria.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atracciones.MsAuditoria.DataAccess.Migrations
{
    [DbContext(typeof(AuditoriaDbContext))]
    partial class AuditoriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atracciones.MsAuditoria.DataAccess.Entities.EventoAuditoriaEntity", b =>
                {
                    b.Property<Guid>("EvtGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("evt_guid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EvtTipo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("evt_tipo");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.HasKey("EvtGuid");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EvtTipo");

                    b.HasIndex("FechaUtc");

                    b.ToTable("eventos", "audit");
                });
#pragma warning restore 612, 618
        }
    }
}
