// <auto-generated />
using System;
using Microservicio.Atracciones.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Microservicio.Atracciones.DataAccess.Migrations
{
    [DbContext(typeof(AtraccionesDbContext))]
    partial class AtraccionesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("atracciones")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Atracciones.AtraccionEntity", b =>
                {
                    b.Property<int>("AtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("AtId"));

                    b.Property<string>("AtDescripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("at_descripcion");

                    b.Property<string>("AtDireccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("at_direccion");

                    b.Property<bool>("AtDisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("at_disponible");

                    b.Property<int?>("AtDuracionMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("at_duracion_minutos");

                    b.Property<char>("AtEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("at_estado");

                    b.Property<DateTime?>("AtFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_fecha_eliminacion");

                    b.Property<DateTime>("AtFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("AtFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_fecha_mod");

                    b.Property<Guid>("AtGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("at_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AtIncluyeAcompaniante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("at_incluye_acompaniante");

                    b.Property<bool>("AtIncluyeTransporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("at_incluye_transporte");

                    b.Property<string>("AtIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("at_ip_eliminacion");

                    b.Property<string>("AtIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("at_ip_ingreso");

                    b.Property<string>("AtIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("at_ip_mod");

                    b.Property<string>("AtNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("at_nombre");

                    b.Property<string>("AtNumEstablecimiento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("at_num_establecimiento");

                    b.Property<decimal?>("AtPrecioReferencia")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("at_precio_referencia");

                    b.Property<string>("AtPuntoEncuentro")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("at_punto_encuentro");

                    b.Property<int>("AtTotalResenias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("at_total_resenias");

                    b.Property<string>("AtUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("at_usuario_eliminacion");

                    b.Property<string>("AtUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("at_usuario_ingreso");

                    b.Property<string>("AtUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("at_usuario_mod");

                    b.Property<int>("DesId")
                        .HasColumnType("integer")
                        .HasColumnName("des_id");

                    b.HasKey("AtId");

                    b.HasIndex("AtGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_atraccion_guid");

                    b.HasIndex("DesId");

                    b.ToTable("atraccion", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Atracciones.AtraccionIncluyeEntity", b =>
                {
                    b.Property<int>("IncId")
                        .HasColumnType("integer")
                        .HasColumnName("inc_id");

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<char>("AiEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("ai_estado");

                    b.Property<DateTime?>("AiFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ai_fecha_eliminacion");

                    b.Property<DateTime>("AiFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ai_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("AiUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ai_usuario_eliminacion");

                    b.Property<string>("AiUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ai_usuario_ingreso");

                    b.HasKey("IncId", "AtId");

                    b.HasIndex("AtId");

                    b.ToTable("atraccion_incluye", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Atracciones.CategoriaAtraccionEntity", b =>
                {
                    b.Property<int>("CatId")
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<char>("CaEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("ca_estado");

                    b.Property<DateTime?>("CaFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ca_fecha_eliminacion");

                    b.Property<DateTime>("CaFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ca_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("CaUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ca_usuario_eliminacion");

                    b.Property<string>("CaUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ca_usuario_ingreso");

                    b.HasKey("CatId", "AtId");

                    b.HasIndex("AtId");

                    b.ToTable("categoria_atraccion", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Atracciones.IdiomaAtraccionEntity", b =>
                {
                    b.Property<int>("IdId")
                        .HasColumnType("integer")
                        .HasColumnName("id_id");

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<char>("IaEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("ia_estado");

                    b.Property<DateTime?>("IaFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ia_fecha_eliminacion");

                    b.Property<DateTime>("IaFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ia_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("IaUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ia_usuario_eliminacion");

                    b.Property<string>("IaUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ia_usuario_ingreso");

                    b.HasKey("IdId", "AtId");

                    b.HasIndex("AtId");

                    b.ToTable("idioma_atraccion", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Atracciones.ImagenAtraccionEntity", b =>
                {
                    b.Property<int>("ImgId")
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<char>("ImaEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("ima_estado");

                    b.Property<DateTime?>("ImaFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ima_fecha_eliminacion");

                    b.Property<DateTime>("ImaFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ima_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("ImaUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ima_usuario_eliminacion");

                    b.Property<string>("ImaUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ima_usuario_ingreso");

                    b.HasKey("ImgId", "AtId");

                    b.HasIndex("AtId");

                    b.ToTable("imagen_atraccion", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Auditoria.AuditoriaLogEntity", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("LogId"));

                    b.Property<string>("LogDatosAnteriores")
                        .HasColumnType("text")
                        .HasColumnName("log_datos_anteriores");

                    b.Property<string>("LogDatosNuevos")
                        .HasColumnType("text")
                        .HasColumnName("log_datos_nuevos");

                    b.Property<DateTime>("LogFechaUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("log_fecha_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("LogGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("LogIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("log_ip");

                    b.Property<string>("LogOperacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("log_operacion");

                    b.Property<string>("LogOrigenCanal")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("log_origen_canal");

                    b.Property<Guid?>("LogRegistroGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("log_registro_guid");

                    b.Property<int?>("LogRegistroId")
                        .HasColumnType("integer")
                        .HasColumnName("log_registro_id");

                    b.Property<string>("LogTabla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("log_tabla");

                    b.Property<string>("LogUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("log_usuario");

                    b.HasKey("LogId");

                    b.HasIndex("LogGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_auditoria_log_guid");

                    b.ToTable("auditoria_log", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Catalogos.CategoriaEntity", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("CatId"));

                    b.Property<char>("CatEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("cat_estado");

                    b.Property<DateTime?>("CatFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cat_fecha_eliminacion");

                    b.Property<DateTime>("CatFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cat_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("CatFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cat_fecha_mod");

                    b.Property<Guid>("CatGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cat_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CatIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cat_ip_eliminacion");

                    b.Property<string>("CatIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cat_ip_ingreso");

                    b.Property<string>("CatIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cat_ip_mod");

                    b.Property<string>("CatNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cat_nombre");

                    b.Property<int?>("CatParentId")
                        .HasColumnType("integer")
                        .HasColumnName("cat_parent_id");

                    b.Property<string>("CatUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cat_usuario_eliminacion");

                    b.Property<string>("CatUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cat_usuario_ingreso");

                    b.Property<string>("CatUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cat_usuario_mod");

                    b.HasKey("CatId");

                    b.HasIndex("CatGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_categoria_guid");

                    b.HasIndex("CatParentId");

                    b.ToTable("categoria", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Catalogos.DestinoEntity", b =>
                {
                    b.Property<int>("DesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("des_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("DesId"));

                    b.Property<char>("DesEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("des_estado");

                    b.Property<DateTime?>("DesFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("des_fecha_eliminacion");

                    b.Property<DateTime>("DesFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("des_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("DesFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("des_fecha_mod");

                    b.Property<Guid>("DesGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("des_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DesImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("des_imagen_url");

                    b.Property<string>("DesIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("des_ip_eliminacion");

                    b.Property<string>("DesIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("des_ip_ingreso");

                    b.Property<string>("DesIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("des_ip_mod");

                    b.Property<string>("DesNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("des_nombre");

                    b.Property<string>("DesPais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("des_pais");

                    b.Property<string>("DesUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("des_usuario_eliminacion");

                    b.Property<string>("DesUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("des_usuario_ingreso");

                    b.Property<string>("DesUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("des_usuario_mod");

                    b.HasKey("DesId");

                    b.HasIndex("DesGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_destino_guid");

                    b.ToTable("destino", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Catalogos.IdiomaEntity", b =>
                {
                    b.Property<int>("IdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IdId"));

                    b.Property<string>("IdDescripcion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("id_descripcion");

                    b.Property<char>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("id_estado");

                    b.Property<DateTime?>("IdFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("id_fecha_eliminacion");

                    b.Property<DateTime>("IdFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("id_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("IdFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("id_fecha_mod");

                    b.Property<Guid>("IdGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("IdIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("id_ip_eliminacion");

                    b.Property<string>("IdIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("id_ip_ingreso");

                    b.Property<string>("IdIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("id_ip_mod");

                    b.Property<string>("IdUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_usuario_eliminacion");

                    b.Property<string>("IdUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_usuario_ingreso");

                    b.Property<string>("IdUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_usuario_mod");

                    b.HasKey("IdId");

                    b.HasIndex("IdDescripcion")
                        .IsUnique()
                        .HasDatabaseName("uk_idioma_descripcion");

                    b.HasIndex("IdGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_idioma_guid");

                    b.ToTable("idioma", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Catalogos.ImagenEntity", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ImgId"));

                    b.Property<string>("ImgDescripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("img_descripcion");

                    b.Property<char>("ImgEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("img_estado");

                    b.Property<DateTime?>("ImgFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("img_fecha_eliminacion");

                    b.Property<DateTime>("ImgFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("img_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("ImgFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("img_fecha_mod");

                    b.Property<Guid>("ImgGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("img_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ImgIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("img_ip_eliminacion");

                    b.Property<string>("ImgIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("img_ip_ingreso");

                    b.Property<string>("ImgIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("img_ip_mod");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("img_url");

                    b.Property<string>("ImgUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("img_usuario_eliminacion");

                    b.Property<string>("ImgUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("img_usuario_ingreso");

                    b.Property<string>("ImgUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("img_usuario_mod");

                    b.HasKey("ImgId");

                    b.HasIndex("ImgGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_imagen_guid");

                    b.ToTable("imagen", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Catalogos.IncluyeEntity", b =>
                {
                    b.Property<int>("IncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IncId"));

                    b.Property<string>("IncDescripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("inc_descripcion");

                    b.Property<char>("IncEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("inc_estado");

                    b.Property<Guid>("IncGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("inc_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("IncId");

                    b.HasIndex("IncGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_incluye_guid");

                    b.ToTable("incluye", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Clientes.ClienteEntity", b =>
                {
                    b.Property<int>("CliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("CliId"));

                    b.Property<string>("CliApellidos")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cli_apellidos");

                    b.Property<string>("CliCorreo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cli_correo");

                    b.Property<string>("CliDireccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cli_direccion");

                    b.Property<char>("CliEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("cli_estado");

                    b.Property<DateTime?>("CliFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cli_fecha_eliminacion");

                    b.Property<DateTime>("CliFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cli_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("CliGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cli_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CliIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cli_ip_eliminacion");

                    b.Property<string>("CliIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cli_ip_ingreso");

                    b.Property<string>("CliNombres")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cli_nombres");

                    b.Property<string>("CliNumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cli_numero_identificacion");

                    b.Property<string>("CliRazonSocial")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cli_razon_social");

                    b.Property<string>("CliTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cli_telefono");

                    b.Property<string>("CliTipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cli_tipo_identificacion");

                    b.Property<string>("CliUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cli_usuario_eliminacion");

                    b.Property<string>("CliUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cli_usuario_ingreso");

                    b.Property<int?>("UsuId")
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    b.HasKey("CliId");

                    b.HasIndex("CliGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_clientes_guid");

                    b.HasIndex("CliNumeroIdentificacion")
                        .IsUnique()
                        .HasDatabaseName("uk_clientes_num_identificacion");

                    b.HasIndex("UsuId")
                        .IsUnique();

                    b.ToTable("clientes", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Facturacion.DatosFacturacionEntity", b =>
                {
                    b.Property<int>("DfacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dfac_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("DfacId"));

                    b.Property<string>("DfacApellido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dfac_apellido");

                    b.Property<string>("DfacCorreo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("dfac_correo");

                    b.Property<Guid>("DfacGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("dfac_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DfacNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dfac_nombre");

                    b.Property<string>("DfacTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dfac_telefono");

                    b.Property<int>("FacId")
                        .HasColumnType("integer")
                        .HasColumnName("fac_id");

                    b.HasKey("DfacId");

                    b.HasIndex("DfacGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_datos_facturacion_guid");

                    b.HasIndex("FacId")
                        .IsUnique()
                        .HasDatabaseName("uk_datos_facturacion_fac");

                    b.ToTable("datos_facturacion", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Facturacion.FacturaEntity", b =>
                {
                    b.Property<int>("FacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fac_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("FacId"));

                    b.Property<char>("FacEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("fac_estado");

                    b.Property<DateTime?>("FacFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fac_fecha_eliminacion");

                    b.Property<DateTime>("FacFechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fac_fecha_emision")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("FacFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fac_fecha_mod");

                    b.Property<Guid>("FacGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fac_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("FacIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("fac_ip_eliminacion");

                    b.Property<string>("FacIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("fac_ip_ingreso");

                    b.Property<string>("FacIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("fac_ip_mod");

                    b.Property<string>("FacMotivoInhabilitacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("fac_motivo_inhabilitacion");

                    b.Property<string>("FacNumero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fac_numero");

                    b.Property<string>("FacObservacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fac_observacion");

                    b.Property<string>("FacOrigenCanal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fac_origen_canal");

                    b.Property<decimal>("FacTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fac_total");

                    b.Property<string>("FacUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fac_usuario_eliminacion");

                    b.Property<string>("FacUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fac_usuario_ingreso");

                    b.Property<string>("FacUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fac_usuario_mod");

                    b.Property<int>("RevId")
                        .HasColumnType("integer")
                        .HasColumnName("rev_id");

                    b.HasKey("FacId");

                    b.HasIndex("FacGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_facturas_guid");

                    b.HasIndex("FacNumero")
                        .IsUnique()
                        .HasDatabaseName("uk_facturas_numero");

                    b.HasIndex("RevId")
                        .IsUnique()
                        .HasDatabaseName("uk_facturas_reserva");

                    b.ToTable("facturas", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Reservas.HorarioEntity", b =>
                {
                    b.Property<int>("HorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("hor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("HorId"));

                    b.Property<int>("HorCuposDisponibles")
                        .HasColumnType("integer")
                        .HasColumnName("hor_cupos_disponibles");

                    b.Property<char>("HorEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("hor_estado");

                    b.Property<DateOnly>("HorFecha")
                        .HasColumnType("date")
                        .HasColumnName("hor_fecha");

                    b.Property<DateTime?>("HorFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hor_fecha_eliminacion");

                    b.Property<DateTime>("HorFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hor_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("HorFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hor_fecha_mod");

                    b.Property<Guid>("HorGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("hor_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<TimeOnly?>("HorHoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hor_hora_fin");

                    b.Property<TimeOnly>("HorHoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hor_hora_inicio");

                    b.Property<string>("HorIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("hor_ip_eliminacion");

                    b.Property<string>("HorIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("hor_ip_ingreso");

                    b.Property<string>("HorIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("hor_ip_mod");

                    b.Property<string>("HorUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hor_usuario_eliminacion");

                    b.Property<string>("HorUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hor_usuario_ingreso");

                    b.Property<string>("HorUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hor_usuario_mod");

                    b.Property<int>("TckId")
                        .HasColumnType("integer")
                        .HasColumnName("tck_id");

                    b.HasKey("HorId");

                    b.HasIndex("HorGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_horario_guid");

                    b.HasIndex("TckId", "HorFecha", "HorHoraInicio")
                        .IsUnique()
                        .HasDatabaseName("uk_horario_slot");

                    b.ToTable("horario", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Reservas.ReseniaEntity", b =>
                {
                    b.Property<int>("RsnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rsn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("RsnId"));

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<int>("RevId")
                        .HasColumnType("integer")
                        .HasColumnName("rev_id");

                    b.Property<string>("RsnComentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rsn_comentario");

                    b.Property<char>("RsnEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("rsn_estado");

                    b.Property<DateTime>("RsnFechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rsn_fecha_creacion")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("RsnFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rsn_fecha_eliminacion");

                    b.Property<DateTime?>("RsnFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rsn_fecha_mod");

                    b.Property<Guid>("RsnGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rsn_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("RsnIpCreacion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rsn_ip_creacion");

                    b.Property<string>("RsnIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rsn_ip_eliminacion");

                    b.Property<string>("RsnIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rsn_ip_mod");

                    b.Property<short>("RsnRating")
                        .HasColumnType("smallint")
                        .HasColumnName("rsn_rating");

                    b.Property<string>("RsnUsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rsn_usuario_creacion");

                    b.Property<string>("RsnUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rsn_usuario_eliminacion");

                    b.Property<string>("RsnUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rsn_usuario_mod");

                    b.HasKey("RsnId");

                    b.HasIndex("AtId");

                    b.HasIndex("RevId")
                        .IsUnique()
                        .HasDatabaseName("uk_resenia_reserva");

                    b.HasIndex("RsnGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_resenia_guid");

                    b.ToTable("resenia", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Reservas.ReservaDetalleEntity", b =>
                {
                    b.Property<int>("RdetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rdet_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("RdetId"));

                    b.Property<int>("RdetCantidad")
                        .HasColumnType("integer")
                        .HasColumnName("rdet_cantidad");

                    b.Property<char>("RdetEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("rdet_estado");

                    b.Property<DateTime?>("RdetFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rdet_fecha_eliminacion");

                    b.Property<DateTime>("RdetFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rdet_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("RdetGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rdet_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("RdetIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rdet_ip_eliminacion");

                    b.Property<string>("RdetIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rdet_ip_ingreso");

                    b.Property<decimal>("RdetPrecioUnit")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("rdet_precio_unit");

                    b.Property<decimal>("RdetSubtotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("rdet_subtotal");

                    b.Property<string>("RdetUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rdet_usuario_eliminacion");

                    b.Property<string>("RdetUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rdet_usuario_ingreso");

                    b.Property<int>("RevId")
                        .HasColumnType("integer")
                        .HasColumnName("rev_id");

                    b.Property<int>("TckId")
                        .HasColumnType("integer")
                        .HasColumnName("tck_id");

                    b.HasKey("RdetId");

                    b.HasIndex("RdetGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_rdet_guid");

                    b.HasIndex("TckId");

                    b.HasIndex("RevId", "TckId")
                        .IsUnique()
                        .HasDatabaseName("uk_rdet_rev_tck");

                    b.ToTable("reserva_detalle", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Reservas.ReservaEntity", b =>
                {
                    b.Property<int>("RevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rev_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("RevId"));

                    b.Property<int>("CliId")
                        .HasColumnType("integer")
                        .HasColumnName("cli_id");

                    b.Property<int>("HorId")
                        .HasColumnType("integer")
                        .HasColumnName("hor_id");

                    b.Property<string>("RevCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rev_codigo");

                    b.Property<char>("RevEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("rev_estado");

                    b.Property<DateTime?>("RevFechaCancelacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rev_fecha_cancelacion");

                    b.Property<DateTime?>("RevFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rev_fecha_mod");

                    b.Property<DateTime>("RevFechaReservaUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rev_fecha_reserva_utc")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("RevGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rev_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("RevIpCancelacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rev_ip_cancelacion");

                    b.Property<string>("RevIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rev_ip_ingreso");

                    b.Property<string>("RevIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rev_ip_mod");

                    b.Property<string>("RevMotivoCancelacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("rev_motivo_cancelacion");

                    b.Property<string>("RevOrigenCanal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rev_origen_canal");

                    b.Property<decimal>("RevSubtotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("rev_subtotal");

                    b.Property<decimal>("RevTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("rev_total");

                    b.Property<string>("RevUsuarioCancelacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rev_usuario_cancelacion");

                    b.Property<string>("RevUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rev_usuario_ingreso");

                    b.Property<string>("RevUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rev_usuario_mod");

                    b.Property<decimal>("RevValorIva")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("rev_valor_iva");

                    b.HasKey("RevId");

                    b.HasIndex("CliId");

                    b.HasIndex("HorId");

                    b.HasIndex("RevCodigo")
                        .IsUnique()
                        .HasDatabaseName("uk_reservas_codigo");

                    b.HasIndex("RevGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_reservas_guid");

                    b.ToTable("reservas", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Reservas.TicketEntity", b =>
                {
                    b.Property<int>("TckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tck_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("TckId"));

                    b.Property<int>("AtId")
                        .HasColumnType("integer")
                        .HasColumnName("at_id");

                    b.Property<int>("TckCapacidadMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("tck_capacidad_maxima");

                    b.Property<int>("TckCuposDisponibles")
                        .HasColumnType("integer")
                        .HasColumnName("tck_cupos_disponibles");

                    b.Property<char>("TckEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("tck_estado");

                    b.Property<DateTime?>("TckFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tck_fecha_eliminacion");

                    b.Property<DateTime>("TckFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tck_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("TckFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tck_fecha_mod");

                    b.Property<Guid>("TckGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tck_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("TckIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tck_ip_eliminacion");

                    b.Property<string>("TckIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tck_ip_ingreso");

                    b.Property<string>("TckIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tck_ip_mod");

                    b.Property<decimal>("TckPrecio")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("tck_precio");

                    b.Property<string>("TckTipoParticipante")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Adulto")
                        .HasColumnName("tck_tipo_participante");

                    b.Property<string>("TckTitulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tck_titulo");

                    b.Property<string>("TckUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tck_usuario_eliminacion");

                    b.Property<string>("TckUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tck_usuario_ingreso");

                    b.Property<string>("TckUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tck_usuario_mod");

                    b.HasKey("TckId");

                    b.HasIndex("AtId");

                    b.HasIndex("TckGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_ticket_guid");

                    b.ToTable("ticket", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Seguridad.RolEntity", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolDescripcion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("rol_descripcion");

                    b.Property<char>("RolEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("rol_estado");

                    b.Property<DateTime?>("RolFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rol_fecha_eliminacion");

                    b.Property<DateTime>("RolFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rol_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("RolGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rol_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("RolIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rol_ip_eliminacion");

                    b.Property<string>("RolIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rol_ip_ingreso");

                    b.Property<string>("RolUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol_usuario_eliminacion");

                    b.Property<string>("RolUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rol_usuario_ingreso");

                    b.HasKey("RolId");

                    b.HasIndex("RolGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_roles_guid");

                    b.ToTable("roles", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Seguridad.UsuarioEntity", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("UsuId"));

                    b.Property<char>("UsuEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("usu_estado");

                    b.Property<DateTime?>("UsuFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usu_fecha_eliminacion");

                    b.Property<DateTime?>("UsuFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usu_fecha_mod");

                    b.Property<DateTime>("UsuFechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usu_fecha_registro")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("UsuGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usu_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("UsuIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("usu_ip_eliminacion");

                    b.Property<string>("UsuIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("usu_ip_mod");

                    b.Property<string>("UsuIpRegistro")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("usu_ip_registro");

                    b.Property<string>("UsuLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usu_login");

                    b.Property<string>("UsuPasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("usu_password_hash");

                    b.Property<string>("UsuUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usu_usuario_eliminacion");

                    b.Property<string>("UsuUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usu_usuario_mod");

                    b.Property<string>("UsuUsuarioRegistro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usu_usuario_registro");

                    b.HasKey("UsuId");

                    b.HasIndex("UsuGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_usuario_guid");

                    b.HasIndex("UsuLogin")
                        .IsUnique()
                        .HasDatabaseName("uk_usuario_login");

                    b.ToTable("usuario", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Seguridad.UsuarioRolEntity", b =>
                {
                    b.Property<int>("UsuRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usu_rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("UsuRolId"));

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<int>("UsuId")
                        .HasColumnType("integer")
                        .HasColumnName("usu_id");

                    b.Property<char>("UsuRolEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("usu_rol_estado");

                    b.HasKey("UsuRolId");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuId", "RolId")
                        .IsUnique()
                        .HasDatabaseName("uk_usuarioxroles_par");

                    b.ToTable("usuarioxroles", "atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Atracciones.AtraccionEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Catalogos.DestinoEntity", "Destino")
                        .WithMany("Atracciones")
                        .HasForeignKey("DesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_atraccion_destino");

                    b.Navigation("Destino");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Atracciones.AtraccionIncluyeEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Atracciones.AtraccionEntity", "Atraccion")
                        .WithMany("AtraccionesIncluyen")
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_atraccion");

                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Catalogos.IncluyeEntity", "Incluye")
                        .WithMany("AtraccionesIncluyen")
                        .HasForeignKey("IncId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_incluye");

                    b.Navigation("Atraccion");

                    b.Navigation("Incluye");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Atracciones.CategoriaAtraccionEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Atracciones.AtraccionEntity", "Atraccion")
                        .WithMany("CategoriasAtracciones")
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ca_atraccion");

                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Catalogos.CategoriaEntity", "Categoria")
                        .WithMany("CategoriasAtracciones")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ca_categoria");

                    b.Navigation("Atraccion");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Atracciones.IdiomaAtraccionEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Atracciones.AtraccionEntity", "Atraccion")
                        .WithMany("IdiomasAtracciones")
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ia_atraccion");

                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Catalogos.IdiomaEntity", "Idioma")
                        .WithMany("IdiomasAtracciones")
                        .HasForeignKey("IdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ia_idioma");

                    b.Navigation("Atraccion");

                    b.Navigation("Idioma");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Atracciones.ImagenAtraccionEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Atracciones.AtraccionEntity", "Atraccion")
                        .WithMany("ImagenesAtracciones")
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ima_atraccion");

                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Catalogos.ImagenEntity", "Imagen")
                        .WithMany("ImagenesAtracciones")
                        .HasForeignKey("ImgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ima_imagen");

                    b.Navigation("Atraccion");

                    b.Navigation("Imagen");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Catalogos.CategoriaEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Catalogos.CategoriaEntity", "Parent")
                        .WithMany("Hijos")
                        .HasForeignKey("CatParentId")
                        .HasConstraintName("fk_categoria_parent");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Clientes.ClienteEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Seguridad.UsuarioEntity", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("Microservicio.Atracciones.DataAccess.Entities.Clientes.ClienteEntity", "UsuId")
                        .HasConstraintName("fk_clientes_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Facturacion.DatosFacturacionEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Facturacion.FacturaEntity", "Factura")
                        .WithOne("DatosFacturacion")
                        .HasForeignKey("Microservicio.Atracciones.DataAccess.Entities.Facturacion.DatosFacturacionEntity", "FacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_datos_facturacion_fac");

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Facturacion.FacturaEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Reservas.ReservaEntity", "Reserva")
                        .WithOne("Factura")
                        .HasForeignKey("Microservicio.Atracciones.DataAccess.Entities.Facturacion.FacturaEntity", "RevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_facturas_reserva");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Reservas.HorarioEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Reservas.TicketEntity", "Ticket")
                        .WithMany("Horarios")
                        .HasForeignKey("TckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_horario_ticket");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Reservas.ReseniaEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Atracciones.AtraccionEntity", "Atraccion")
                        .WithMany("Resenias")
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resenia_atraccion");

                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Reservas.ReservaEntity", "Reserva")
                        .WithOne("Resenia")
                        .HasForeignKey("Microservicio.Atracciones.DataAccess.Entities.Reservas.ReseniaEntity", "RevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resenia_reserva");

                    b.Navigation("Atraccion");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Reservas.ReservaDetalleEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Reservas.ReservaEntity", "Reserva")
                        .WithMany("ReservasDetalle")
                        .HasForeignKey("RevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rdet_reserva");

                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Reservas.TicketEntity", "Ticket")
                        .WithMany("ReservasDetalle")
                        .HasForeignKey("TckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rdet_ticket");

                    b.Navigation("Reserva");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Reservas.ReservaEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Clientes.ClienteEntity", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("CliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservas_cliente");

                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Reservas.HorarioEntity", "Horario")
                        .WithMany("Reservas")
                        .HasForeignKey("HorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservas_horario");

                    b.Navigation("Cliente");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Reservas.TicketEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Atracciones.AtraccionEntity", "Atraccion")
                        .WithMany("Tickets")
                        .HasForeignKey("AtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_atraccion");

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Seguridad.UsuarioRolEntity", b =>
                {
                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Seguridad.RolEntity", "RolEntity")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarioxroles_rol");

                    b.HasOne("Microservicio.Atracciones.DataAccess.Entities.Seguridad.UsuarioEntity", "UsuEntity")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("UsuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarioxroles_usuario");

                    b.Navigation("RolEntity");

                    b.Navigation("UsuEntity");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Atracciones.AtraccionEntity", b =>
                {
                    b.Navigation("AtraccionesIncluyen");

                    b.Navigation("CategoriasAtracciones");

                    b.Navigation("IdiomasAtracciones");

                    b.Navigation("ImagenesAtracciones");

                    b.Navigation("Resenias");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Catalogos.CategoriaEntity", b =>
                {
                    b.Navigation("CategoriasAtracciones");

                    b.Navigation("Hijos");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Catalogos.DestinoEntity", b =>
                {
                    b.Navigation("Atracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Catalogos.IdiomaEntity", b =>
                {
                    b.Navigation("IdiomasAtracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Catalogos.ImagenEntity", b =>
                {
                    b.Navigation("ImagenesAtracciones");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Catalogos.IncluyeEntity", b =>
                {
                    b.Navigation("AtraccionesIncluyen");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Clientes.ClienteEntity", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Facturacion.FacturaEntity", b =>
                {
                    b.Navigation("DatosFacturacion");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Reservas.HorarioEntity", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Reservas.ReservaEntity", b =>
                {
                    b.Navigation("Factura");

                    b.Navigation("Resenia");

                    b.Navigation("ReservasDetalle");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Reservas.TicketEntity", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("ReservasDetalle");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Seguridad.RolEntity", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("Microservicio.Atracciones.DataAccess.Entities.Seguridad.UsuarioEntity", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
