// <auto-generated />
using System;
using Atracciones.MsAtracciones.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atracciones.MsAtracciones.DataAccess.Migrations
{
    [DbContext(typeof(InventarioDbContext))]
    partial class InventarioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventario")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionCategoriaEntity", b =>
                {
                    b.Property<Guid>("AtGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("at_guid");

                    b.Property<Guid>("CatGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("cat_guid");

                    b.Property<char>("CaEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("ca_estado");

                    b.Property<DateTime>("CaFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ca_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("CaUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ca_usuario_ingreso");

                    b.HasKey("AtGuid", "CatGuid");

                    b.ToTable("atraccion_categoria", "inventario");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionEntity", b =>
                {
                    b.Property<Guid>("AtGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("at_guid");

                    b.Property<string>("AtDescripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("at_descripcion");

                    b.Property<string>("AtDireccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("at_direccion");

                    b.Property<bool>("AtDisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("at_disponible");

                    b.Property<int?>("AtDuracionMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("at_duracion_minutos");

                    b.Property<char>("AtEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("at_estado");

                    b.Property<DateTime?>("AtFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_fecha_eliminacion");

                    b.Property<DateTime>("AtFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("AtFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_fecha_mod");

                    b.Property<bool>("AtIncluyeAcompaniante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("at_incluye_acompaniante");

                    b.Property<bool>("AtIncluyeTransporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("at_incluye_transporte");

                    b.Property<string>("AtIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("at_ip_eliminacion");

                    b.Property<string>("AtIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("at_ip_ingreso");

                    b.Property<string>("AtIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("at_ip_mod");

                    b.Property<string>("AtNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("at_nombre");

                    b.Property<string>("AtNumEstablecimiento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("at_num_establecimiento");

                    b.Property<decimal?>("AtPrecioReferencia")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("at_precio_referencia");

                    b.Property<string>("AtPuntoEncuentro")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("at_punto_encuentro");

                    b.Property<int>("AtTotalResenias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("at_total_resenias");

                    b.Property<string>("AtUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("at_usuario_eliminacion");

                    b.Property<string>("AtUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("at_usuario_ingreso");

                    b.Property<string>("AtUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("at_usuario_mod");

                    b.Property<Guid>("DesGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("des_guid");

                    b.Property<string>("DesNombreSnap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("des_nombre_snap");

                    b.Property<string>("DesPaisSnap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("des_pais_snap");

                    b.HasKey("AtGuid");

                    b.ToTable("atracciones", "inventario");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionIdiomaEntity", b =>
                {
                    b.Property<Guid>("AtGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdGuid")
                        .HasColumnType("uuid");

                    b.Property<char>("IaEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("ia_estado");

                    b.Property<DateTime>("IaFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ia_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("IaUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ia_usuario_ingreso");

                    b.Property<string>("IdDescripcionSnap")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("id_descripcion_snap");

                    b.HasKey("AtGuid", "IdGuid");

                    b.ToTable("atraccion_idioma", "inventario");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionImagenEntity", b =>
                {
                    b.Property<Guid>("AtGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImgGuid")
                        .HasColumnType("uuid");

                    b.Property<char>("ImaEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("ima_estado");

                    b.Property<DateTime>("ImaFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ima_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("ImaOrden")
                        .HasColumnType("integer")
                        .HasColumnName("ima_orden");

                    b.Property<string>("ImaUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ima_usuario_ingreso");

                    b.Property<string>("ImgUrlSnap")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("img_url_snap");

                    b.HasKey("AtGuid", "ImgGuid");

                    b.ToTable("atraccion_imagen", "inventario");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionIncluyeEntity", b =>
                {
                    b.Property<Guid>("AtGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IncGuid")
                        .HasColumnType("uuid");

                    b.Property<char>("AiEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("ai_estado");

                    b.Property<DateTime>("AiFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ai_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("AiUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ai_usuario_ingreso");

                    b.Property<string>("IncDescripcionSnap")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("inc_descripcion_snap");

                    b.HasKey("AtGuid", "IncGuid");

                    b.ToTable("atraccion_incluye", "inventario");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.HorarioEntity", b =>
                {
                    b.Property<Guid>("HorGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("hor_guid");

                    b.Property<int>("HorCuposDisponibles")
                        .HasColumnType("integer")
                        .HasColumnName("hor_cupos_disponibles");

                    b.Property<char>("HorEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("hor_estado");

                    b.Property<DateOnly>("HorFecha")
                        .HasColumnType("date")
                        .HasColumnName("hor_fecha");

                    b.Property<DateTime?>("HorFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hor_fecha_eliminacion");

                    b.Property<DateTime>("HorFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hor_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("HorFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hor_fecha_mod");

                    b.Property<TimeOnly?>("HorHoraFin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hor_hora_fin");

                    b.Property<TimeOnly>("HorHoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hor_hora_inicio");

                    b.Property<string>("HorIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("hor_ip_eliminacion");

                    b.Property<string>("HorIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("hor_ip_ingreso");

                    b.Property<string>("HorIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("hor_ip_mod");

                    b.Property<string>("HorUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hor_usuario_eliminacion");

                    b.Property<string>("HorUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hor_usuario_ingreso");

                    b.Property<string>("HorUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hor_usuario_mod");

                    b.Property<Guid>("TckGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("tck_guid");

                    b.HasKey("HorGuid");

                    b.HasIndex("TckGuid", "HorFecha", "HorHoraInicio")
                        .IsUnique()
                        .HasDatabaseName("uk_horario_slot");

                    b.ToTable("horarios", "inventario");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.ReseniaEntity", b =>
                {
                    b.Property<Guid>("RsnGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("rsn_guid");

                    b.Property<Guid>("AtGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("at_guid");

                    b.Property<Guid>("RevGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("rev_guid");

                    b.Property<string>("RsnComentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rsn_comentario");

                    b.Property<char>("RsnEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("rsn_estado");

                    b.Property<DateTime>("RsnFechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rsn_fecha_creacion")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("RsnFechaEliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RsnFechaMod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RsnIpCreacion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("rsn_ip_creacion");

                    b.Property<string>("RsnIpEliminacion")
                        .HasColumnType("text");

                    b.Property<string>("RsnIpMod")
                        .HasColumnType("text");

                    b.Property<decimal>("RsnRating")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rsn_rating");

                    b.Property<string>("RsnUsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rsn_usuario_creacion");

                    b.Property<string>("RsnUsuarioEliminacion")
                        .HasColumnType("text");

                    b.Property<string>("RsnUsuarioMod")
                        .HasColumnType("text");

                    b.HasKey("RsnGuid");

                    b.HasIndex("AtGuid");

                    b.HasIndex("RevGuid")
                        .IsUnique()
                        .HasDatabaseName("uk_resenia_rev_guid");

                    b.ToTable("resenias", "inventario");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.TicketEntity", b =>
                {
                    b.Property<Guid>("TckGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tck_guid");

                    b.Property<Guid>("AtGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("at_guid");

                    b.Property<int>("TckCapacidadMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("tck_capacidad_maxima");

                    b.Property<int>("TckCuposDisponibles")
                        .HasColumnType("integer")
                        .HasColumnName("tck_cupos_disponibles");

                    b.Property<char>("TckEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue('A')
                        .HasColumnName("tck_estado");

                    b.Property<DateTime?>("TckFechaEliminacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tck_fecha_eliminacion");

                    b.Property<DateTime>("TckFechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tck_fecha_ingreso")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime?>("TckFechaMod")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tck_fecha_mod");

                    b.Property<string>("TckIpEliminacion")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tck_ip_eliminacion");

                    b.Property<string>("TckIpIngreso")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tck_ip_ingreso");

                    b.Property<string>("TckIpMod")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tck_ip_mod");

                    b.Property<decimal>("TckPrecio")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("tck_precio");

                    b.Property<string>("TckTipoParticipante")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Adulto")
                        .HasColumnName("tck_tipo_participante");

                    b.Property<string>("TckTitulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tck_titulo");

                    b.Property<string>("TckUsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tck_usuario_eliminacion");

                    b.Property<string>("TckUsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tck_usuario_ingreso");

                    b.Property<string>("TckUsuarioMod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tck_usuario_mod");

                    b.HasKey("TckGuid");

                    b.HasIndex("AtGuid");

                    b.ToTable("tickets", "inventario");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionCategoriaEntity", b =>
                {
                    b.HasOne("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionEntity", "Atraccion")
                        .WithMany("Categorias")
                        .HasForeignKey("AtGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionIdiomaEntity", b =>
                {
                    b.HasOne("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionEntity", "Atraccion")
                        .WithMany("Idiomas")
                        .HasForeignKey("AtGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionImagenEntity", b =>
                {
                    b.HasOne("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionEntity", "Atraccion")
                        .WithMany("Imagenes")
                        .HasForeignKey("AtGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionIncluyeEntity", b =>
                {
                    b.HasOne("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionEntity", "Atraccion")
                        .WithMany("Incluyes")
                        .HasForeignKey("AtGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.HorarioEntity", b =>
                {
                    b.HasOne("Atracciones.MsAtracciones.DataAccess.Entities.TicketEntity", "Ticket")
                        .WithMany("Horarios")
                        .HasForeignKey("TckGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.ReseniaEntity", b =>
                {
                    b.HasOne("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionEntity", "Atraccion")
                        .WithMany("Resenias")
                        .HasForeignKey("AtGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.TicketEntity", b =>
                {
                    b.HasOne("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionEntity", "Atraccion")
                        .WithMany("Tickets")
                        .HasForeignKey("AtGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atraccion");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.AtraccionEntity", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Idiomas");

                    b.Navigation("Imagenes");

                    b.Navigation("Incluyes");

                    b.Navigation("Resenias");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Atracciones.MsAtracciones.DataAccess.Entities.TicketEntity", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
