<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Atracciones.MsAtracciones.Api</RootNamespace>
    <UserSecretsId>atracciones-ms-atracciones</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.67.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.14.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="..\..\..\..\platform\shared\Contracts.Protos\atraccion_inventario_service.proto" GrpcServices="Server" Link="Protos\atraccion_inventario_service.proto" />
    <Protobuf Include="..\..\..\..\platform\shared\Contracts.Protos\catalogo_service.proto" GrpcServices="Server" Link="Protos\catalogo_service.proto" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Atracciones.MsAtracciones.Business\Atracciones.MsAtracciones.Business.csproj" />
    <ProjectReference Include="..\Atracciones.MsAtracciones.DataAccess\Atracciones.MsAtracciones.DataAccess.csproj" />
  </ItemGroup>
</Project>
